### PR TITLE
Adding the Pythagoras Tree

### PR DESCRIPTION
**Pull request by npx**
This took me longer than I would love to admin, but long gone are the days of rotation matrices haha

Check it out @trebeljahr

### CODE REVIEW

**Comment by trebeljahr** [comment]
haha long gone are the days of rotation matrices - what a lovely way to express it ^^ 

I have a closer look now, but from a first glance this looks good :+1:

**Comment by trebeljahr** [comment]
I have one suggestion before we can merge this – namely I think it would be *really* cool if the colors get lighter when moving toward the "leafs" of the tree, as of now I find the shade of green a bit too uniform + the fractal nature of the tree isn't as beautiful/apparent because of that. 

You can use the remapper you factored out for this and remap for a value that smoothly goes from 0-1 for each iteration and then use that to map the rgbs from start to end colors to achieve this effect (pretty much what is happening on the fractal canopy already). Maybe this code could be factored out and re-used :+1: 

image
Something like this from Wikipedia would be extra super premium, but I would be fine with a simple color map already :blush: 

Something that could be cool as a follow-up/extra and shouldn't be *too* hard to do (if you want you can even do it in this PR) is to add an option to draw the tree from an image, like this (which is an image of Pythagoras and I love the self-referential humor in that haha)

image

**Comment by npx** [comment]
Hi @trebeljahr 

would you be so kind as to label my PRs as "hacktoberfest-accepted" while I finish up to get a chance for that sweet sweet Tshirt? That would be lovely!

Regarding the color fade: can do! I'll get right on it!

Regarding the picture: scaling, rotating and drawing the image for the trunk should be doable.
I assume you do not mean to allow "any" picture. While technically possible, it would come with additional challenges that I think we should not face.

Also, what about making that picure rendering an "easteregg"? Like when you hit aabbcc or ccaabb it will render as such and make an option appear to toggle back? :D 

What do you think?

**Comment by npx** [comment]
Implemented the gradient:

image

Also, I added the option to keep the squares empty, which i think looks neat as well:

image

I also paused the animation for 2s in its final step so you can enjoy the tree for a bit more.

Let me know what you think!

**Comment by trebeljahr** [comment]
just wow! the work with the Pythagoras tree is awesome! 

Now it looks really really cool :blush: 

I like the easter egg idea, maybe hint at it somehow from the text though so it's discoverable :+1: it's a bit too awesome to keep it hidden like this (at least that's what's my feeling). Let's create a separate issue for that though and handle it apart from this PR. 

as for your request toward the hacktoberfest-accepted label, I am looking into how to do this (still relatively new to this whole open source "maintainer" game ^^) but we'll get you that T-shirt!

**Comment by trebeljahr** [comment]
image

let me know if that did the trick for you :+1:

**Comment by trebeljahr** [comment]
just one last thing on this: 
image

if you could change the image to match the grey colors of the other fractals on the home page, as of now this looks a bit odd with the black background...

**Comment by trebeljahr** [comment]
+ maybe make the aspect ratio of the image, such that it shows nicely on most screens – i.e. square aspect ratio + leaving little bits of space around the left/right parts of the tree so that it shows completely and isn't cut off at the edges.

**Comment by trebeljahr** [comment]
> While technically possible, it would come with additional challenges that I think we should not face.

I agree with that. Not in this PR for sure. 

Would be super duper cool though, but at some other time, linked to some other issue. I know the Sierpinski Triangle also has this property that you can start out with any image and still get the fractal shape out of it, so code for uploading/maintaining pictures could even be shared among multiple fractals. 

Not sure if a picture can be held in localStorage/memory somehow so that there is no S3 integration necessary. But again, discussion for another time ^^

**Comment by npx** [comment]
Yes will fix that, I shouldnt have played with the colors before haha

**Comment by npx** [comment]
Thanks for the labelling. As I understand you only need to label what as not been merged, as we can see you are approving of the MR but it takes a bit more to adopt it.

However it seems to be too late for the shirt now haha but I have contacted them.
By the way your activiy as a maintainer (labeling the mrs and accepting them) should also make you eligible for completion so you might want to check that out! This is my fourth hacktober fest :)

**Comment by trebeljahr** [comment]
image

@npx just curious because I just saw that you are not showing as a contributor on the main page of this repo... maybe that's why the contributions also didn't count towards the hacktober fest? :confused: 

Dug up thus:
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#common-reasons-that-contributions-are-not-counted

**Comment by npx** [comment]
Hi @trebeljahr 

The condition for accepting a contribution are that the PR must be created and either merged or labelled by the end of october.
My other 2 PRs were counted, as you merged them within october. The remaining two you labeled in November and thus the Hacktoberfest Team does not count them. That is what they confirmed in an E-Mail exchange we had.

I am still waiting on a further elaboration.

Nonetheless, it was great fun to contribute to your project!

About the contributors setting you mentioned, it does not affect hacktoberfest at all!

Thank you and I will get you that image by tomorrow, as I usually have my dev evenings on wednesdays!

Cheers!

**Comment by npx** [comment]
Hi @trebeljahr 

I've updated the thumbnail according to your recommendation.

Cheers

**Comment by trebeljahr** [comment]
Hi @npx, 
I merged this now :) everything looks good, thanks for all the work you put into this – it's beautiful! :heart:

**Pull request merged**
